In [98]:
data2
# Apply , map , vectorised functions


import pandas as pd
import numpy as np


data = np.round(np.random.normal(size=(4, 3)), 2)


In [99]:
df = pd.DataFrame(data, columns=["A", "B", "C"])
df.head()

A     B     C
0  0.60  0.78  0.22
1 -0.63  0.02  1.16
2  0.12 -0.63 -1.96
3  0.30  0.56  0.44

In [100]:
df.apply(lambda x: 1 + np.abs(x))

A     B     C
0  1.60  1.78  1.22
1  1.63  1.02  2.16
2  1.12  1.63  2.96
3  1.30  1.56  1.44

In [101]:
# Map, Similar to apply but operators on Series, and uses dictionary based inputs rather an array of values.

In [102]:
series = pd.Series(["Steve", "Jess", "Mark"])
# Map just runs at series , not Dataframes.
series.map({"Steve": "Stephen"})


0    Stephen
1        NaN
2        NaN
dtype: object

In [103]:
series.map(lambda d: f'I am {d}')

0    I am Steve
1     I am Jess
2     I am Mark
dtype: object

In [104]:
series.str.upper().str.split()

0    [STEVE]
1     [JESS]
2     [MARK]
dtype: object

In [105]:
# User defined functions 
# Sample : How to find a hipotenuse given a X and Y.


In [121]:
data2 = np.random.normal(10, 2, size=(10000, 2))
data2

array([[10.95041235,  6.85200081],
       [ 8.93833535, 11.80463661],
       [ 6.52004086, 10.57455348],
       ...,
       [ 8.0041374 ,  9.5189817 ],
       [ 9.24817912,  7.35777814],
       [10.47201147,  9.82973846]])

In [117]:

df2 = pd.DataFrame(data2, columns=["x", "y"])
df2

x          y
0     11.859578   9.028280
1      8.450847   9.934714
2      5.440003   9.551912
3     12.183401   6.479096
4      9.730236  10.649234
...         ...        ...
9995  10.215880  10.829427
9996   6.923849   6.814505
9997   9.571261  10.770516
9998   8.409807  11.513654
9999  11.456355  12.334365

[10000 rows x 2 columns]

In [118]:
hypot = (df2.x**2 + df2.y**2)**0.5
print(hypot[0])


14.90501302351295


In [109]:
data2

array([[11.85957765,  9.02827953],
       [ 8.45084673,  9.93471401],
       [ 5.44000317,  9.55191184],
       ...,
       [ 9.57126147, 10.77051554],
       [ 8.40980702, 11.51365364],
       [11.45635535, 12.3343654 ]])

In [110]:
data2

array([[11.85957765,  9.02827953],
       [ 8.45084673,  9.93471401],
       [ 5.44000317,  9.55191184],
       ...,
       [ 9.57126147, 10.77051554],
       [ 8.40980702, 11.51365364],
       [11.45635535, 12.3343654 ]])

In [116]:
def hypot3(xs, ys):
    return np.sqrt(xs**2 + ys**2)


h3 = hypot3(df2.x, df2.y)
print(h3[0])
h3

14.90501302351295


0       14.905013
1       13.042828
2       10.992391
3       13.799056
4       14.425105
          ...    
9995    14.887602
9996     9.714791
9997    14.408784
9998    14.257948
9999    16.834032
Length: 10000, dtype: float64